In [1]:
import pandas as pd

movies = pd.read_csv('movies.csv')

print(movies.head())

      title   genres                            overview
0  Avengers   Action           Superhero saves the world
1  Iron Man   Action  Marvel hero builds a powerful suit
2   Titanic  Romance      A love story on a sinking ship
3      Thor   Action       God of thunder protects earth

In [2]:
movies["tags"] = movies["genres"] + " " + movies["overview"] 

movies.head()

,title,genres,overview,tags
0,Avengers,Action,Superhero saves the world,Action Superhero saves the world
1,Iron Man,Action,Marvel hero builds a powerful suit,Action Marvel hero builds a powerful suit
2,Titanic,Romance,A love story on a sinking ship,Romance A love story on a sinking ship
3,Thor,Action,God of thunder protects earth,Action God of thunder protects earth

In [3]:
movies = movies[['title','tags']]

movies.head()

      title                                       tags
0  Avengers           Action Superhero saves the world
1  Iron Man  Action Marvel hero builds a powerful suit
2   Titanic     Romance A love story on a sinking ship
3      Thor       Action God of thunder protects earth

In [4]:
movies['tags'] = movies['tags'].apply(lambda x: x.lower())

In [ ]:
#Vectorization 
# Text -> Numbers
#Vocabulary

In [6]:
from sklearn.feature_extraction.text import CountVectorizer 
cv = CountVectorizer(max_features=5000, stop_words="english")

vectors = cv.fit_transform(movies["tags"]).toarray()

In [7]:
vectors

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]],
      dtype=int64)

In [9]:
#Cosine Similarity 

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)
similarity

array([[1.        , 0.20412415, 0.        , 0.2236068 ],
       [0.20412415, 1.        , 0.        , 0.18257419],
       [0.        , 0.        , 1.        , 0.        ],
       [0.2236068 , 0.18257419, 0.        , 1.        ]])

In [10]:
movies.head()

      title                                       tags
0  Avengers           action superhero saves the world
1  Iron Man  action marvel hero builds a powerful suit
2   Titanic     romance a love story on a sinking ship
3      Thor       action god of thunder protects earth

In [12]:
movies[movies["title"] == "Avengers"].index[0]

0

In [13]:
similarity[0]

array([1.        , 0.20412415, 0.        , 0.2236068 ])

In [15]:
def recommend(movie):

    index = movies[movies["title"] == movie].index[0]

    distances = similarity[index]

    movie_list = sorted(list(enumerate(distances)),
                        reverse=True,
                        key=lambda x: x[1])[1:6]

    for i in movie_list:
        print(movies.iloc[i[0]].title)

In [16]:
recommend("Avengers")

Thor
Iron Man
Titanic